/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class inas_smart_CHASM_DEVMODE */

#ifndef _Included_inas_smart_CHASM_DEVMODE
#define _Included_inas_smart_CHASM_DEVMODE
#ifdef __cplusplus
extern "C" {
#endif
#undef inas_smart_CHASM_DEVMODE_SMART_MAG_BUFFER
#define inas_smart_CHASM_DEVMODE_SMART_MAG_BUFFER 1024L
#ifdef __cplusplus
}
#endif
#endif
