/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class inas_smart_SmartPrinterList */

#ifndef _Included_inas_smart_SmartPrinterList
#define _Included_inas_smart_SmartPrinterList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
